/* eslint-disable no-mixed-spaces-and-tabs */
import * as React from "react";
import { Image, TouchableOpacity } from "react-native";
import { Container, Header, Content, Text, Button, Left, Right, Body, View, H1, H2 } from "native-base";
// import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import MaterialCommunityIcon from "react-native-vector-icons/MaterialCommunityIcons";
import EntypoIcon from "react-native-vector-icons/Entypo";
import styles from "./styles";
class ContentPage extends React.Component {
    render() {
        const param = this.props.navigation.state.params;
        return (React.createElement(Container, { style: styles.container },
            React.createElement(Header, null,
                React.createElement(Left, null,
                    React.createElement(Button, { transparent: true, onPress: () => this.props.navigation.goBack() },
                        React.createElement(MaterialCommunityIcon, { name: "keyboard-backspace", style: { fontSize: 22, color: "#fff" } }))),
                React.createElement(Body, { style: { flex: 3 } }),
                React.createElement(Right, null,
                    React.createElement(Button, { transparent: true },
                        React.createElement(MaterialCommunityIcon, { name: "magnify", style: { fontSize: 22, color: "#fff" } })),
                    React.createElement(Button, { transparent: true },
                        React.createElement(MaterialCommunityIcon
                        // active
                        , { 
                            // active
                            name: "share-variant", style: { fontSize: 22, color: "#fff" } })))),
            React.createElement(Content, { style: { padding: 0 } },
                React.createElement(Image, { style: styles.content_img, source: require("../../../../assets/a.jpg") }),
                React.createElement(View, { style: styles.content_wrapper, style: { flexDirection: "column", paddingLeft: 15, paddingRight: 15, } },
                    React.createElement(View, { style: styles.content_view },
                        React.createElement(TouchableOpacity, { style: { marginLeft: -15, paddingLeft: 15, marginRight: -15, paddingRight: 15, backgroundColor: "#ccc", paddingTop: 5, paddingBottom: 5, marginBottom: 10 } },
                            React.createElement(Text, { style: { fontWeight: "bold", fontSize: 21, fontFamily: "Roboto" } },
                                "\u0110\u00E1nh gi\u00E1 pin Huawei Mate 20: t\u1ED1t, onscreen g\u1EA7n 7 ti\u1EBFng, s\u1EA1c nhanh 22.5W",
                                React.createElement(MaterialCommunityIcon, { name: "arrow-down-drop-circle-outline", style: { color: "#16bdd8", fontSize: 21, marginLeft: 15 } }))),
                        React.createElement(View, { style: { flexDirection: "row", justifyContent: "space-between", marginBottom: 10 } },
                            React.createElement(Image, { style: styles.img, source: require("../../../../assets/a.jpg"), resizeMode: "cover", borderRadius: 25 }),
                            React.createElement(View, { style: { marginLeft: -220 } },
                                React.createElement(Text, null, "Drchuottui"),
                                React.createElement(Text, null, "16:43")),
                            React.createElement(MaterialCommunityIcon, { name: "dots-vertical", style: { fontSize: 22, color: "#000" } })),
                        React.createElement(Text, null, "Huawei Mate 20 \u0111\u01B0\u1EE3c trang b\u1ECB vi\u00EAn pin dung l\u01B0\u1EE3ng 4.000 mAh v\u00E0 n\u00F3 \u0111\u1EE7 \u0111\u1EC3 thi\u1EBFt b\u1ECB n\u00E0y c\u00F3 th\u1EC3 on screen li\u00EAn t\u1EE5c trong g\u1EA7n 7 ti\u1EBFng v\u1EDBi c\u00E1c t\u00E1c v\u1EE5 th\u1EF1c hi\u1EC7n h\u1ED7n h\u1EE3p. \u01AF\u1EDBc t\u00EDnh cho th\u1EA5y th\u1EDDi gian ch\u01A1i game li\u00EAn t\u1EE5c (c\u1EA3 game offline v\u00E0 game online) v\u00E0o kho\u1EA3ng h\u01A1n 6 ti\u1EBFng, th\u1EDDi gian duy\u1EC7t web li\u00EAn t\u1EE5c h\u01A1n 6 ti\u1EBFng r\u01B0\u1EE1i, trong khi th\u1EDDi gian xem phim \u0111\u1EA1t \u0111\u01B0\u1EE3c l\u00E0 kho\u1EA3ng 8 ti\u1EBFng r\u01B0\u1EE1i."),
                        React.createElement(Image, { style: [styles.content_img, styles.img_space], source: require("../../../../assets/b.jpg") }),
                        React.createElement(View, { style: styles.view_path },
                            React.createElement(H1, null, "TH\u00D4NG S\u1ED0 C\u01A0 B\u1EA2N M\u00C1Y IN NH\u00C3N TEPRA PRO"),
                            React.createElement(Text, null, "M\u00E3 h\u00E0ng: Tepra Pro SR-R170V"),
                            React.createElement(Text, null, "\u0110\u1ED9 r\u1ED9ng nh\u00E3n in: 4mm - 6mm - 9mm - 12mm - 18mm"),
                            React.createElement(Text, null, "Kh\u1ED1i l\u01B0\u1EE3ng m\u00E1y kh\u00F4ng c\u00F3 b\u0103ng nh\u00E3n v\u00E0 pin: 580g"),
                            React.createElement(Text, null, "D\u00F9ng ngu\u1ED3n \u0111i\u1EC7n: S\u1EA1c AC ho\u1EB7c 6pin AA")),
                        React.createElement(Image, { style: [styles.content_img, styles.img_space], source: require("../../../../assets/b.jpg") }),
                        React.createElement(View, { style: styles.view_path },
                            React.createElement(H1, null, "3 THAO T\u00C1C S\u1EEC D\u1EE4NG \u0110\u01A0N GI\u1EA2N"),
                            React.createElement(Text, null, "M\u00ECnh ch\u1EC9 m\u1EA5t 5 ph\u00FAt \u0111\u1EC3 c\u00F3 th\u1EC3 in c\u00E1i nh\u00E3n \u0111\u1EA7u ti\u00EAn. R\u1EA5t d\u1EC5 s\u1EED d\u1EE5ng. M\u00E1y c\u00F3 m\u1ED9t b\u00E0n ph\u00EDm \u0111\u1EE7 l\u1EDBn \u0111\u1EC3 b\u1EA5m ch\u1EEF nh\u1EADp li\u1EC7u, ch\u1EEF v\u00E0 c\u00E1c th\u00F4ng tin hi\u1EC3n th\u1ECB tr\u00EAn m\u00E0n h\u00ECnh, m\u00ECnh th\u1EA5y h\u01A1i nh\u1ECF, l\u1EDBn h\u01A1n ch\u00FAt th\u00EC d\u1EC5 nh\u00ECn h\u01A1n. M\u1ECDi thao t\u00E1c hi\u1EC3n th\u1ECB tr\u00EAn m\u00E0n h\u00ECnh, ch\u1EC9nh s\u1EEDa v\u00E0 thay \u0111\u1ED5i v\u1EDBi b\u00E0n ph\u00EDm.")),
                        React.createElement(Image, { style: [styles.content_img, styles.img_space], source: require("../../../../assets/b.jpg") }),
                        React.createElement(View, { style: styles.view_path },
                            React.createElement(H2, null, "Nh\u1EADn \u0111\u1ECBnh:"),
                            React.createElement(Text, null, "C\u00E1 nh\u00E2n m\u00ECnh r\u1EA5t th\u00EDch c\u00E1i m\u00E1y in nh\u00E3n n\u00E0y. L\u00FD do th\u1EE9 nh\u1EA5t l\u00E0 s\u1EED d\u1EE5ng \u0111\u01A1n gi\u1EA3n v\u00E0 \u00EDt m\u1EA5t th\u1EDDi gian cho vi\u1EC7c c\u1EA7n m\u1ED9t c\u00E1i nh\u00E3n d\u00F9ng \u0111\u1EC3 ph\u00E2n lo\u1EA1i, ghi ch\u00FA c\u00E1c c\u00F4ng vi\u1EC7c h\u00E0ng ng\u00E0y, in \u1EA3nh, note... M\u00E0 n\u00F3 c\u00F3 th\u1EC3 ph\u00F9 h\u1EE3p v\u1EDBi b\u1EA5t k\u1EF3 ai v\u00E0 vi\u1EC7c g\u00EC. Th\u1EE9 hai l\u00E0 c\u00F3 ng\u00F4n ng\u1EEF ti\u1EBFng Vi\u1EC7t chu\u1EA9n, kh\u00F4ng co gi\u1EADt b\u00F3p nh\u1ECF c\u00E1c nguy\u00EAn \u00E2m c\u00F3 d\u1EA5u. C\u00E1c l\u00FD do ph\u1EE5 l\u00E0 ki\u1EC3u ch\u1EEF khung vi\u1EC1n c\u0169ng gi\u00FAp m\u00E0u m\u00E8 hoa l\u00E1 khi r\u1EA3nh c\u00F3 th\u1EC3 d\u00F9ng nhi\u1EC1u h\u01A1n cho vi\u1EC7c s\u1EAFp x\u1EBFp \u0111\u1ED3 d\u00F9ng trong nh\u00E0 v\u00E0 n\u01A1i l\u00E0m vi\u1EC7c.")),
                        React.createElement(Image, { style: [styles.content_img, styles.img_space], source: require("../../../../assets/b.jpg") })),
                    React.createElement(View, { style: styles.content_footer },
                        React.createElement(Button, { transparent: true },
                            React.createElement(Text, null, "Like")),
                        React.createElement(EntypoIcon, { name: "dot-single", style: { fontSize: 22, color: "#000" } }),
                        React.createElement(MaterialCommunityIcon, { name: "heart-outline", style: { fontSize: 22, color: "#000" } }),
                        React.createElement(Text, null, "9"),
                        React.createElement(EntypoIcon, { name: "dot-single", style: { fontSize: 22, color: "#000" } }),
                        React.createElement(Button, { transparent: true },
                            React.createElement(Text, null, "Reply"))),
                    React.createElement(View, { style: styles.tags },
                        React.createElement(Text, null, "Tags: "),
                        React.createElement(Text, { style: { backgroundColor: "#ccc", marginRight: 4, marginBottom: 4 } }, "may in nhan tepra pro "),
                        React.createElement(Text, { style: { backgroundColor: "#ccc", marginRight: 4, marginBottom: 4 } }, "may in rubang"),
                        React.createElement(Text, { style: { backgroundColor: "#ccc", marginRight: 4, marginBottom: 4 } }, "May in bang nhan"),
                        React.createElement(Text, { style: { backgroundColor: "#ccc", marginRight: 4, marginBottom: 4 } }, "may in decal"))),
                React.createElement(View, { style: styles.comment_wrapper },
                    React.createElement(View, { style: styles.comment },
                        React.createElement(View, { style: styles.comment_content },
                            React.createElement(Image, { style: styles.img, source: require("../../../../assets/a.jpg"), resizeMode: "cover", borderRadius: 25 }),
                            React.createElement(View, null,
                                React.createElement(Text, null, "Drchuottui"),
                                React.createElement(Text, null, "May nay gia bao nhieu ?"))),
                        React.createElement(View, { style: styles.content_footer },
                            React.createElement(Button, { transparent: true },
                                React.createElement(Text, null, "Hom qua luc 21:20")),
                            React.createElement(EntypoIcon, { name: "dot-single", style: { fontSize: 22, color: "#000" } }),
                            React.createElement(Button, { transparent: true },
                                React.createElement(Text, null, "Like")),
                            React.createElement(EntypoIcon, { name: "dot-single", style: { fontSize: 22, color: "#000" } }),
                            React.createElement(Button, { transparent: true },
                                React.createElement(Text, null, "Reply")))),
                    React.createElement(View, { style: styles.reply },
                        React.createElement(View, { style: styles.comment_content },
                            React.createElement(Image, { style: styles.img, source: require("../../../../assets/a.jpg"), resizeMode: "cover", borderRadius: 25 }),
                            React.createElement(View, null,
                                React.createElement(Text, null, "Drchuottui"),
                                React.createElement(Text, null, "Bac thu hoi thang xem chu em cung khong biet ro..."))),
                        React.createElement(View, { style: styles.content_footer },
                            React.createElement(Button, { transparent: true },
                                React.createElement(Text, null, "Hom qua luc 22:50")),
                            React.createElement(EntypoIcon, { name: "dot-single", style: { fontSize: 22, color: "#000" } }),
                            React.createElement(Button, { transparent: true },
                                React.createElement(Text, null, "Like")),
                            React.createElement(EntypoIcon, { name: "dot-single", style: { fontSize: 22, color: "#000" } }),
                            React.createElement(Button, { transparent: true },
                                React.createElement(Text, null, "Reply"))))),
                React.createElement(View, { style: styles.comment_wrapper },
                    React.createElement(View, { style: styles.comment },
                        React.createElement(View, { style: styles.comment_content },
                            React.createElement(Image, { style: styles.img, source: require("../../../../assets/a.jpg"), resizeMode: "cover", borderRadius: 25 }),
                            React.createElement(View, null,
                                React.createElement(Text, null, "Drchuottui"),
                                React.createElement(Text, null, "May nay gia bao nhieu ?"))),
                        React.createElement(View, { style: styles.content_footer },
                            React.createElement(Button, { transparent: true },
                                React.createElement(Text, null, "Hom qua luc 21:20")),
                            React.createElement(EntypoIcon, { name: "dot-single", style: { fontSize: 22, color: "#000" } }),
                            React.createElement(Button, { transparent: true },
                                React.createElement(Text, null, "Like")),
                            React.createElement(EntypoIcon, { name: "dot-single", style: { fontSize: 22, color: "#000" } }),
                            React.createElement(Button, { transparent: true },
                                React.createElement(Text, null, "Reply")))),
                    React.createElement(View, { style: styles.reply },
                        React.createElement(View, { style: styles.comment_content },
                            React.createElement(Image, { style: styles.img, source: require("../../../../assets/a.jpg"), resizeMode: "cover", borderRadius: 25 }),
                            React.createElement(View, null,
                                React.createElement(Text, null, "Drchuottui"),
                                React.createElement(Text, null, "Bac thu hoi thang xem chu em cung khong biet ro..."))),
                        React.createElement(View, { style: styles.content_footer },
                            React.createElement(Button, { transparent: true },
                                React.createElement(Text, null, "Hom qua luc 22:50")),
                            React.createElement(EntypoIcon, { name: "dot-single", style: { fontSize: 22, color: "#000" } }),
                            React.createElement(Button, { transparent: true },
                                React.createElement(Text, null, "Like")),
                            React.createElement(EntypoIcon, { name: "dot-single", style: { fontSize: 22, color: "#000" } }),
                            React.createElement(Button, { transparent: true },
                                React.createElement(Text, null, "Reply"))))))));
    }
}
export default ContentPage;
//# sourceMappingURL=index.js.map